# nginx proxy address - http://172.17.0.1:8103

name: caddy
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  app:
    image: caddy:latest
    pull_policy: always
    container_name: caddy-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    logging: *default-logging
    networks:
      - caddy
    ports:
      - "172.17.0.1:8103:80"
      - "172.17.0.1:8104:443"
    environment:
      TZ: ${TZ:-America/New_York}
    volumes:
      - ./volumes/config/caddy:/config
      - ./volumes/data/caddy:/data

networks:
  caddy:
    name: caddy
    external: false
